---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app-deploy
        
    spec: 
      containers:
        - name: nginx-app
          image: nginx
          ports:
            - containerPort: 80	
