---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-app-deploy
        
    spec: 
      containers:
        - name: hello-app
          image: nginx
          ports:
            - containerPort: 80	
