apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend                                 # 2
spec:                                                # 3
  containers:
    - image: haridasksd/sentiment-analysis-frontend # 4
      name: sa-frontend
      #      imagePullPolicy: IfNotPresent      # 5
      imagePullPolicy: Always
      ports:
        - containerPort: 80                          # 6
