apiVersion: v1
kind: Service
metadata:
  name: kubernetes-tutorial-cluster-ip
spec:
  selector:
    app: kubernetes-tutorial-deployment
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000

