apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy
  namespace: my-namespace
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80

